#!/usr/bin/env bash

set -euo pipefail
_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
if [[  -f "${_path}/_dm-helper.sh" ]]; then
  # shellcheck disable=SC1090,SC1091
  source "${_path}/_dm-helper.sh"
else
  # shellcheck disable=SC1090
  echo "No helper-script found"
fi

source "$(get_config)"

select_path() {
echo 1	
}

main() {

clip=$(xclip -sel c -o)
echo "$clip" 

choice=$(echo -e "yt\nwget" | ${DMENU} "Save to: ")

if [ "$choice" == "yt" ]; then
  echo "$clip" >> ${HOME}/workspace/nextcloud/shared-folder/download-queue/youtube.txt
  echo -e $(<${HOME}/workspace/nextcloud/Shared\ Folder/download-queue/youtube.txt)
elif [ "$choice" == "wget" ]; then
  echo "$clip" >> ${HOME}/workspace/nextcloud/shared-folder/download-queue/url.txt
  echo -e $(<${HOME}/workspace/nextcloud/Shared\ Folder/download-queue/url.txt)
fi
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
